apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
    image: cirros
    resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
    command: ["/bin/sh", "-c", "env"]
    envFrom:
      - configMapRef:
          name: variables
