apiVersion: v1
kind: Pod
metadata:
  name: vol2
spec:
  containers:
  - name: centos2
    image: centos:7
    command:
      - sleep
      - "3600"
    resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
    volumeMounts:
    - mountPath: /test
      name: test
  restartPolicy: Always
  volumes:
    - name: test
      emptyDir: {}
