apiVersion: v1
kind: Pod
metadata:
  name: busyboxab
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy1
    resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
    command:
    - sleep 
    - "3600"
    volumeMounts:
    - mountPath: /dir
      name: myvolume
  volumes:
  - name: myvolume
    emptyDir: {}
