kind: Pod
apiVersion: v1
metadata:
   name: nfs-pv-pod
spec:
  volumes:
    - name: nfs-pv
      persistentVolumeClaim:
        claimName: nfs-pv-claim
  containers:
    - name: nfs-client1
      image: centos:latest
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: "/nfsshare"
          name: nfs-pv
    - name: nfs-client2
      image: centos:latest
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
      command:
        - sleep
        - "3600"
      volumeMounts:
        - mountPath: "/nfsshare"
          name: nfs-pv
